stop:
  description: Stop the WebSocket connection to the EdgeOS device

restart:
  description: Restart the WebSocket connection to the EdgeOS device

save_debug_data:
  description: "Store the EdgeOS state to file, Path in CONFIG_PATH/edgeos_data.log"

log_events:
  description: "Enable / Disable log of all event messages from WebSocket (DEBUG)"
  fields:
    enabled:
      description: "True / False - whether to log as DEBUG all events"
      example: "true"
      values:
        - true
        - false
